name: Do Release
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'The release version to publish'
        required: true
        default: ''

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Read tag from pushed tag
        if: github.event_name == 'push'
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Read tag from version to publish
        if: github.event_name == 'workflow_dispatch'
        run: echo "tag=${{ github.event.inputs.VERSION }}" >> $GITHUB_ENV

      - name: Set Git Tag for workflow dispatched
        if: github.event_name == 'workflow_dispatch'
        run: |
          git tag ${{ env.tag }} -m "Release ${{ env.tag }}"
          git push origin ${{ env.tag }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.2'

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

